# Generated by Django 3.2.12 on 2022-04-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Сумма покупок',
                'verbose_name_plural': 'Сумма покупок',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('detail.purchases',),
        ),
    ]
