# Generated by Django 3.2.12 on 2022-04-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_purchasessummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='supliers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный товар или нет'),
        ),
    ]
