# Generated by Django 3.2.12 on 2022-04-05 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_auto_20220406_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedDetails',
            fields=[
            ],
            options={
                'verbose_name': 'Удаленная деталь',
                'verbose_name_plural': 'Удаленные детали',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('detail.details',),
        ),
        migrations.CreateModel(
            name='DeletedSupplierDetails',
            fields=[
            ],
            options={
                'verbose_name': 'Удаленные детали поставщиков',
                'verbose_name_plural': 'Удаленные детали поставщиков',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('detail.supplierdetails',),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный товар или нет'),
        ),
        migrations.AlterField(
            model_name='supliers',
            name='phone_number',
            field=models.CharField(help_text='Например +795271941111', max_length=16, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо вводить в формате: «+999999999». Допускается до 15 цифр.', regex='^\\+\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
    ]
