# Generated by Django 3.2.12 on 2022-04-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0005_auto_20220406_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdetails',
            name='deleted_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время удаления'),
        ),
    ]
