# Generated by Django 3.2.12 on 2022-04-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0006_supplierdetails_deleted_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='vendore_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
